import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({
  stdin: {
    contents: "module.exports = { extractZip: require('extract-zip'), openZip: require('yauzl').open };",
    resolveDir: root,
    sourcefile: 'extract-zip-entry.cjs',
  },
  bundle: true, platform: 'node', target: 'node22', format: 'cjs',
  write: false, metafile: true, legalComments: 'inline',
});
const artifacts = new Map([['extract-zip.cjs', result.outputFiles[0].text]]);
const packages = [...new Set(Object.keys(result.metafile.inputs).map((input) => {
  const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
  return match?.[1];
}).filter(Boolean))].sort();
let notices = '# Bundled extraction dependency licenses\n\nGenerated by scripts/build-vendor.mjs from locked dependencies.\n';
for (const name of packages) {
  const dir = path.join(root, 'node_modules', name);
  const pkg = JSON.parse(await readFile(path.join(dir, 'package.json'), 'utf8'));
  let license;
  for (const filename of ['LICENSE', 'LICENSE.md', 'license', 'license.md']) {
    try { license = await readFile(path.join(dir, filename), 'utf8'); break; }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
  if (!license) throw new Error(`Missing license for ${name}`);
  notices += `\n## ${name}@${pkg.version} (${pkg.license})\n\n${license.trim()}\n`;
}
artifacts.set('LICENSES.md', notices);
await mkdir(path.join(root, 'vendor'), { recursive: true });
for (const [filename, content] of artifacts) {
  const target = path.join(root, 'vendor', filename);
  if (process.argv.includes('--check')) {
    if (await readFile(target, 'utf8') !== content) throw new Error(`Rebuild vendor/${filename}`);
  } else await writeFile(target, content);
}
